export const incident_users = [
    {
        "id": 87,
        "version": 1,
        "shortCode": "ANUSHKA.BANDARA@HOIST.TECH",
        "name": "Anushka Bandara",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "anushka.bandara@hoist.tech",
        "email": "anushka.bandara@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 88,
        "version": 1,
        "shortCode": "ABDALLAH.ABDALLAH@HOIST.TECH",
        "name": "Abdallah Abdallah",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "abdallah.abdallah@hoist.tech",
        "email": "abdallah.abdallah@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 89,
        "version": 3,
        "shortCode": "AAN.DESILVA@HOIST.TECH",
        "name": "Aan De Silva",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "aan.desilva@hoist.tech",
        "email": "aan.desilva@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 90,
        "version": 1,
        "shortCode": "ANUKI.KUMARASINGHE@HOIST.TECH",
        "name": "Anuki Kumarasinghe",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "anuki.kumarasinghe@hoist.tech",
        "email": "anuki.kumarasinghe@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 91,
        "version": 1,
        "shortCode": "AKILA.PERERA@HOIST.TECH",
        "name": "Akila Perera",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "akila.perera@hoist.tech",
        "email": "akila.perera@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 92,
        "version": 1,
        "shortCode": "AATHIF.IMTHIYAZ@HOIST.TECH",
        "name": "Aathif Imthiyaz",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "aathif.imthiyaz@hoist.tech",
        "email": "aathif.imthiyaz@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 93,
        "version": 1,
        "shortCode": "AASIF.IQBAL@HOIST.TECH",
        "name": "Aasif Iqbal",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "aasif.iqbal@hoist.tech",
        "email": "aasif.iqbal@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 95,
        "version": 1,
        "shortCode": "ARUNALU.WEERASINGHE@HOIST.TECH",
        "name": "Arunalu Weerasinghe",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "arunalu.weerasinghe@hoist.tech",
        "email": "arunalu.weerasinghe@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 97,
        "version": 1,
        "shortCode": "AUSTIN.WALSH@HOIST.TECH",
        "name": "Austin Walsh",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "austin.walsh@hoist.tech",
        "email": "austin.walsh@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 99,
        "version": 1,
        "shortCode": "ASHNI.NAYANTHARA@HOIST.TECH",
        "name": "Ashni Nayanthara",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "ashni.nayanthara@hoist.tech",
        "email": "ashni.nayanthara@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 100,
        "version": 1,
        "shortCode": "BHANUKA.PERERA@HOIST.TECH",
        "name": "Bhanuka Perera",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "bhanuka.perera@hoist.tech",
        "email": "bhanuka.perera@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 101,
        "version": 1,
        "shortCode": "CHAMIKA.DILHANI@HOIST.TECH",
        "name": "Chamika Dilhani",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "chamika.dilhani@hoist.tech",
        "email": "chamika.dilhani@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 102,
        "version": 1,
        "shortCode": "CHAMATH.KURUPPUARACHCHI@HOIST.TECH",
        "name": "Chamath Kuruppuarachchi",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "chamath.kuruppuarachchi@hoist.tech",
        "email": "chamath.kuruppuarachchi@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 103,
        "version": 1,
        "shortCode": "BOB.MARKUS@HOIST.TECH",
        "name": "Bob Markus",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "bob.markus@hoist.tech",
        "email": "bob.markus@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 104,
        "version": 1,
        "shortCode": "CHANDIMA.PATHIRANA@HOIST.TECH",
        "name": "Chandima Pathirana",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "chandima.pathirana@hoist.tech",
        "email": "chandima.pathirana@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 106,
        "version": 1,
        "shortCode": "CHARITH.KANGARA@HOIST.TECH",
        "name": "Charith Kangara",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "charith.kangara@hoist.tech",
        "email": "charith.kangara@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 108,
        "version": 1,
        "shortCode": "DAMITH.PEIRIS@HOIST.TECH",
        "name": "Damith Peiris",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "damith.peiris@hoist.tech",
        "email": "damith.peiris@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 109,
        "version": 1,
        "shortCode": "DAMITH.JAYAWARDANA@HOIST.TECH",
        "name": "Damith Jayawardana",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "damith.jayawardana@hoist.tech",
        "email": "damith.jayawardana@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 110,
        "version": 1,
        "shortCode": "DANIEL.HASSAN@HOIST.TECH",
        "name": "Daniel Hassan",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "daniel.hassan@hoist.tech",
        "email": "daniel.hassan@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 111,
        "version": 1,
        "shortCode": "DANIEL.TRUJILLO@HOIST.TECH",
        "name": "Daniel Trujillo",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "daniel.trujillo@hoist.tech",
        "email": "daniel.trujillo@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 113,
        "version": 1,
        "shortCode": "DANUKA.NAVARATHNA@HOIST.TECH",
        "name": "Danuka Navarathna",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "danuka.navarathna@hoist.tech",
        "email": "danuka.navarathna@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 114,
        "version": 1,
        "shortCode": "DAYADRA.DHARMASENA@HOIST.TECH",
        "name": "Dayadra Dharmasena",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "dayadra.dharmasena@hoist.tech",
        "email": "dayadra.dharmasena@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 115,
        "version": 1,
        "shortCode": "DILRANGI.THARAKA@HOIST.TECH",
        "name": "Dilrangi Tharaka",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "dilrangi.tharaka@hoist.tech",
        "email": "dilrangi.tharaka@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 117,
        "version": 1,
        "shortCode": "ERANDA.WICKRAMASURIYA@HOIST.TECH",
        "name": "Eranda Wickramasuriya",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "eranda.wickramasuriya@hoist.tech",
        "email": "eranda.wickramasuriya@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 119,
        "version": 1,
        "shortCode": "ESTEBAN.ANAYA@HOIST.TECH",
        "name": "Esteban Anaya",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "esteban.anaya@hoist.tech",
        "email": "esteban.anaya@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 121,
        "version": 1,
        "shortCode": "FERNANDO.SAVIOLLI@HOIST.TECH",
        "name": "Fernando Saviolli",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "fernando.saviolli@hoist.tech",
        "email": "fernando.saviolli@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 122,
        "version": 1,
        "shortCode": "GHAZALI.ISMAIL@HOIST.TECH",
        "name": "Ghazali Ismail",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "ghazali.ismail@hoist.tech",
        "email": "ghazali.ismail@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 123,
        "version": 1,
        "shortCode": "GHAZI.ISMAIL@HOIST.TECH",
        "name": "Ghazi Ismail",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "ghazi.ismail@hoist.tech",
        "email": "ghazi.ismail@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 124,
        "version": 1,
        "shortCode": "GRACE.MONTALVO@HOIST.TECH",
        "name": "Grace Montalvo",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "grace.montalvo@hoist.tech",
        "email": "grace.montalvo@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 125,
        "version": 1,
        "shortCode": "GUILHERME.GILS@HOIST.TECH",
        "name": "Guilherme Gils",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "guilherme.gils@hoist.tech",
        "email": "guilherme.gils@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 126,
        "version": 1,
        "shortCode": "GUADALUPE.CERVANTES@HOIST.TECH",
        "name": "Guadalupe Cervantes",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "guadalupe.cervantes@hoist.tech",
        "email": "guadalupe.cervantes@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 128,
        "version": 1,
        "shortCode": "HANSIKA.GAYANTHI@HOIST.TECH",
        "name": "Hansika Gayanthi",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "hansika.gayanthi@hoist.tech",
        "email": "hansika.gayanthi@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 129,
        "version": 1,
        "shortCode": "HARSHA.CHANDRASENA@HOIST.TECH",
        "name": "Harsha Chandrasena",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "harsha.chandrasena@hoist.tech",
        "email": "harsha.chandrasena@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 131,
        "version": 1,
        "shortCode": "HARSHA.JAYASURIYA@HOIST.TECH",
        "name": "Harsha Madhushan",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "harsha.jayasuriya@hoist.tech",
        "email": "harsha.jayasuriya@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 132,
        "version": 1,
        "shortCode": "IFHAM.ABDEEN@HOIST.TECH",
        "name": "Ifham Abdeen",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "ifham.abdeen@hoist.tech",
        "email": "ifham.abdeen@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 133,
        "version": 1,
        "shortCode": "HESHANI.NANAYAKKARA@HOIST.TECH",
        "name": "Heshani Nanayakkara",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "heshani.nanayakkara@hoist.tech",
        "email": "heshani.nanayakkara@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 134,
        "version": 1,
        "shortCode": "INDIKA.WICKREMASEKARA@HOIST.TECH",
        "name": "Indika Wickremaskara",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "indika.wickremasekara@hoist.tech",
        "email": "indika.wickremasekara@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 135,
        "version": 1,
        "shortCode": "INDUWARA.JAYASUNDARA@HOIST.TECH",
        "name": "Induwara Jayasundara",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "induwara.jayasundara@hoist.tech",
        "email": "induwara.jayasundara@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 136,
        "version": 1,
        "shortCode": "INSAF.INTIZAM@HOIST.TECH",
        "name": "Insaf Intizam",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "insaf.intizam@hoist.tech",
        "email": "insaf.intizam@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 137,
        "version": 1,
        "shortCode": "ISHARD.CASSIM@HOIST.TECH",
        "name": "Ishard Cassim",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "ishard.cassim@hoist.tech",
        "email": "ishard.cassim@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 138,
        "version": 1,
        "shortCode": "ISURI.GALLAGE@HOIST.TECH",
        "name": "Isuri Gallage",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "isuri.gallage@hoist.tech",
        "email": "isuri.gallage@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 141,
        "version": 1,
        "shortCode": "JAWAD.TIMANI@HOIST.TECH",
        "name": "Jawad Timani",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "jawad.timani@hoist.tech",
        "email": "jawad.timani@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 142,
        "version": 1,
        "shortCode": "JANINE.HALEPIAN@HOIST.TECH",
        "name": "Janine Halepian",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "janine.halepian@hoist.tech",
        "email": "janine.halepian@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 143,
        "version": 1,
        "shortCode": "JANANI.DENIPITIYA@HOIST.TECH",
        "name": "Janani Denipitiya",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "janani.denipitiya@hoist.tech",
        "email": "janani.denipitiya@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 145,
        "version": 1,
        "shortCode": "JENIFER.WAGNER@HOIST.TECH",
        "name": "Jenifer Wagner",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "jenifer.wagner@hoist.tech",
        "email": "jenifer.wagner@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 146,
        "version": 1,
        "shortCode": "JIM.LEBEL@HOIST.TECH",
        "name": "Jim Lebel",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "jim.lebel@hoist.tech",
        "email": "jim.lebel@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 147,
        "version": 1,
        "shortCode": "JISHU.DAS@HOIST.TECH",
        "name": "Jishu Das",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "jishu.das@hoist.tech",
        "email": "jishu.das@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 148,
        "version": 1,
        "shortCode": "KANISHKA.UNDUGODAPATHIRANA@HOIST.TECH",
        "name": "Kanishka Undugodapathirana",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "kanishka.undugodapathirana@hoist.tech",
        "email": "kanishka.undugodapathirana@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 149,
        "version": 1,
        "shortCode": "JUAN.MARRIAGA@HOIST.TECH",
        "name": "Juan Marriaga",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "juan.marriaga@hoist.tech",
        "email": "juan.marriaga@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 150,
        "version": 1,
        "shortCode": "KALSHA.ATHUKORALA@HOIST.TECH",
        "name": "Kalsha Athukorala",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "kalsha.athukorala@hoist.tech",
        "email": "kalsha.athukorala@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 151,
        "version": 1,
        "shortCode": "KANISHKA.WEERASEKARA@HOIST.TECH",
        "name": "Kanishka Weerasekara",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "kanishka.weerasekara@hoist.tech",
        "email": "kanishka.weerasekara@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 152,
        "version": 1,
        "shortCode": "JOSE.DIAZ@HOIST.TECH",
        "name": "Jose Diaz",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "jose.diaz@hoist.tech",
        "email": "jose.diaz@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 153,
        "version": 1,
        "shortCode": "KAVINDI.WEWALWALA@HOIST.TECH",
        "name": "Kavindi Wewalwala",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "kavindi.wewalwala@hoist.tech",
        "email": "kavindi.wewalwala@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 154,
        "version": 1,
        "shortCode": "KEERTHIGAN.PUSHPARAJ@HOIST.TECH",
        "name": "Keerthigan Pushparaj",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "keerthigan.pushparaj@hoist.tech",
        "email": "keerthigan.pushparaj@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 155,
        "version": 1,
        "shortCode": "LAKNA.HAKMANAARACHCHI@HOIST.TECH",
        "name": "Lakna Hakmanaarachchi",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "lakna.hakmanaarachchi@hoist.tech",
        "email": "lakna.hakmanaarachchi@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 157,
        "version": 1,
        "shortCode": "LAURA.GUARIN@HOIST.TECH",
        "name": "Laura Guarin",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "laura.guarin@hoist.tech",
        "email": "laura.guarin@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 158,
        "version": 1,
        "shortCode": "LAKSHIKA.GAMINI@HOIST.TECH",
        "name": "Lakshika Gamini",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "lakshika.gamini@hoist.tech",
        "email": "lakshika.gamini@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 159,
        "version": 1,
        "shortCode": "LAKSHA.DAMPAHALA@HOIST.TECH",
        "name": "Laksha Dampahala",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "laksha.dampahala@hoist.tech",
        "email": "laksha.dampahala@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 160,
        "version": 1,
        "shortCode": "LAURA.SALAZAR@HOIST.TECH",
        "name": "Laura Salazar",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "laura.salazar@hoist.tech",
        "email": "laura.salazar@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 161,
        "version": 1,
        "shortCode": "LUCIANA.NUNES@HOIST.TECH",
        "name": "Luciana Nunes",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "luciana.nunes@hoist.tech",
        "email": "luciana.nunes@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 162,
        "version": 1,
        "shortCode": "LUIS.CADAVID@HOIST.TECH",
        "name": "Luis Cadavid Urieta",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "luis.cadavid@hoist.tech",
        "email": "luis.cadavid@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 164,
        "version": 1,
        "shortCode": "LUISA.ESCOBAR@HOIST.TECH",
        "name": "Luisa Escobar",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "luisa.escobar@hoist.tech",
        "email": "luisa.escobar@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 165,
        "version": 1,
        "shortCode": "MANUEL.EBRAT@HOIST.TECH",
        "name": "Manuel Ebrat",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "manuel.ebrat@hoist.tech",
        "email": "manuel.ebrat@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 166,
        "version": 1,
        "shortCode": "MARIA.PENARANDA@HOIST.TECH",
        "name": "Maria Penaranda",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "maria.penaranda@hoist.tech",
        "email": "maria.penaranda@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 167,
        "version": 1,
        "shortCode": "MICHAEL.MEANY@HOIST.TECH",
        "name": "Michael meany",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "michael.meany@hoist.tech",
        "email": "michael.meany@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 168,
        "version": 1,
        "shortCode": "MICHELLE.DEYONGH@HOIST.TECH",
        "name": "Michelle Deyongh",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "michelle.deyongh@hoist.tech",
        "email": "michelle.deyongh@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 170,
        "version": 1,
        "shortCode": "MOHAMED.AJMAL@HOIST.TECH",
        "name": "Mohamed Ajmal",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "mohamed.ajmal@hoist.tech",
        "email": "mohamed.ajmal@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 171,
        "version": 1,
        "shortCode": "NAJIB.ELHUSSEINI@HOIST.TECH",
        "name": "Najib Elhusseini",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "najib.elhusseini@hoist.tech",
        "email": "najib.elhusseini@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 172,
        "version": 1,
        "shortCode": "NAYOMI.KARIYAWASAM@HOIST.TECH",
        "name": "Nayomi Kariyawasam",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "nayomi.kariyawasam@hoist.tech",
        "email": "nayomi.kariyawasam@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 173,
        "version": 1,
        "shortCode": "NEMANTHI.EDIRISOORIYA@HOIST.TECH",
        "name": "Nemanthi Edirisooriya",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "nemanthi.edirisooriya@hoist.tech",
        "email": "nemanthi.edirisooriya@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 174,
        "version": 1,
        "shortCode": "NIPUNI.PERERA@HOIST.TECH",
        "name": "Nipuni Perera",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "nipuni.perera@hoist.tech",
        "email": "nipuni.perera@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 175,
        "version": 1,
        "shortCode": "NEMER.HABIB@HOIST.TECH",
        "name": "Nemer Habib",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "nemer.habib@hoist.tech",
        "email": "nemer.habib@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 176,
        "version": 1,
        "shortCode": "NIYOMAL.NATHANIELSZ@HOIST.TECH",
        "name": "Niyomal Nathanielsz",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "niyomal.nathanielsz@hoist.tech",
        "email": "niyomal.nathanielsz@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 177,
        "version": 1,
        "shortCode": "NIRMAL.THILAKARATHNE@HOIST.TECH",
        "name": "Nirmal Thilakarathne",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "nirmal.thilakarathne@hoist.tech",
        "email": "nirmal.thilakarathne@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 178,
        "version": 1,
        "shortCode": "NIRUSHI.RODRIGO@HOIST.TECH",
        "name": "Nirushi Rodrigo",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "nirushi.rodrigo@hoist.tech",
        "email": "nirushi.rodrigo@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 179,
        "version": 1,
        "shortCode": "PASINDU.RUCKSHAN@HOIST.TECH",
        "name": "Pasindu Ruckshan",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "pasindu.ruckshan@hoist.tech",
        "email": "pasindu.ruckshan@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 180,
        "version": 1,
        "shortCode": "OALUMALI.SIRISENA@HOIST.TECH",
        "name": "Oalumali Sirisena",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "oalumali.sirisena@hoist.tech",
        "email": "oalumali.sirisena@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 181,
        "version": 1,
        "shortCode": "PATRICIA.ROJAS@HOIST.TECH",
        "name": "Patricia Rojas",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "patricia.rojas@hoist.tech",
        "email": "patricia.rojas@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 182,
        "version": 1,
        "shortCode": "PEDRO.ARROYO@HOIST.TECH",
        "name": "Pedro Arroyo",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "pedro.arroyo@hoist.tech",
        "email": "pedro.arroyo@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 183,
        "version": 1,
        "shortCode": "PETER.GHOSSEIN@HOIST.TECH",
        "name": "Peter Ghossein",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "peter.ghossein@hoist.tech",
        "email": "peter.ghossein@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 184,
        "version": 1,
        "shortCode": "PIYUMI.DISSANAYAKE@HOIST.TECH",
        "name": "Piyumi Dissanayake",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "piyumi.dissanayake@hoist.tech",
        "email": "piyumi.dissanayake@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 185,
        "version": 1,
        "shortCode": "POORNIMA.MADUWANTHI@HOIST.TECH",
        "name": "Poornima Maduwanthi",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "poornima.maduwanthi@hoist.tech",
        "email": "poornima.maduwanthi@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 186,
        "version": 1,
        "shortCode": "PRABHAVI.WIJAYASEKARA@HOIST.TECH",
        "name": "Prabhavi Wijayasekara",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "prabhavi.wijayasekara@hoist.tech",
        "email": "prabhavi.wijayasekara@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 187,
        "version": 3,
        "shortCode": "PRABHA.RUBERU@HOIST.TECH",
        "name": "Prabha Ruberu",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "prabha.ruberu@hoist.tech",
        "email": "prabha.ruberu@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 189,
        "version": 1,
        "shortCode": "RALPH.ALSAYAH@HOIST.TECH",
        "name": "Ralph Al Sayah",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "ralph.alsayah@hoist.tech",
        "email": "ralph.alsayah@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 191,
        "version": 1,
        "shortCode": "REMI.SAYAH@HOIST.TECH",
        "name": "Remi Sayah",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "remi.sayah@hoist.tech",
        "email": "remi.sayah@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 194,
        "version": 1,
        "shortCode": "RICHARD.WOODS@HOIST.TECH",
        "name": "Richard Woods",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "richard.woods@hoist.tech",
        "email": "richard.woods@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 197,
        "version": 1,
        "shortCode": "RITA.ASLO@HOIST.TECH",
        "name": "Rita Aslo",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "rita.aslo@hoist.tech",
        "email": "rita.aslo@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 198,
        "version": 1,
        "shortCode": "RUWANTHIKA.PREMALAL@HOIST.TECH",
        "name": "Ruwanthika Premalal",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "ruwanthika.premalal@hoist.tech",
        "email": "ruwanthika.premalal@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 199,
        "version": 1,
        "shortCode": "SACHITH.BANDARA@HOIST.TECH",
        "name": "Sachith Bandara",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "sachith.bandara@hoist.tech",
        "email": "sachith.bandara@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 200,
        "version": 1,
        "shortCode": "SACHITHA.DESILVA@HOIST.TECH",
        "name": "Sachitha DeSilva",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "sachitha.desilva@hoist.tech",
        "email": "sachitha.desilva@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 202,
        "version": 1,
        "shortCode": "SANDRA.LOZADA@HOIST.TECH",
        "name": "Sandra Lozada",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "sandra.lozada@hoist.tech",
        "email": "sandra.lozada@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 203,
        "version": 1,
        "shortCode": "SANEEKA.WIJESINGHE@HOIST.TECH",
        "name": "Saneeka Wijesinghe",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "saneeka.wijesinghe@hoist.tech",
        "email": "saneeka.wijesinghe@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 204,
        "version": 1,
        "shortCode": "SANTHISRI.VUPPALA@HOIST.TECH",
        "name": "Santhisri Vuppala",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "santhisri.vuppala@hoist.tech",
        "email": "santhisri.vuppala@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 205,
        "version": 1,
        "shortCode": "SAPUMAL.MAYURANGA@HOIST.TECH",
        "name": "Sapumal Mayuranga",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "sapumal.mayuranga@hoist.tech",
        "email": "sapumal.mayuranga@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 206,
        "version": 1,
        "shortCode": "SAWANTHA.JAYASIRI@HOIST.TECH",
        "name": "Sawantha Jayasiri",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "sawantha.jayasiri@hoist.tech",
        "email": "sawantha.jayasiri@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 207,
        "version": 1,
        "shortCode": "SELIM.NASRALLAH@HOIST.TECH",
        "name": "Selim Nasrallah",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "selim.nasrallah@hoist.tech",
        "email": "selim.nasrallah@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 208,
        "version": 1,
        "shortCode": "SAVINI.MADURASINGHE@HOIST.TECH",
        "name": "Savini Madurasinghe",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "savini.madurasinghe@hoist.tech",
        "email": "savini.madurasinghe@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 211,
        "version": 1,
        "shortCode": "SHENITH.FERNANDO@HOIST.TECH",
        "name": "Shenith Fernando",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "shenith.fernando@hoist.tech",
        "email": "shenith.fernando@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 212,
        "version": 1,
        "shortCode": "SHIRLYS.AMAYA@HOIST.TECH",
        "name": "Shirlys Amaya",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "shirlys.amaya@hoist.tech",
        "email": "shirlys.amaya@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 213,
        "version": 1,
        "shortCode": "SITHIJA.LIYANAGAMAGE@HOIST.TECH",
        "name": "Sithija Liyanagamage",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "sithija.liyanagamage@hoist.tech",
        "email": "sithija.liyanagamage@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 214,
        "version": 1,
        "shortCode": "SUGANDI.NADEESHIKA@HOIST.TECH",
        "name": "Sugandi Nadeeshika",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "sugandi.nadeeshika@hoist.tech",
        "email": "sugandi.nadeeshika@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 217,
        "version": 1,
        "shortCode": "THOMAS.SOUBLIERE@HOIST.TECH",
        "name": "Thomas Soubliere",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "thomas.soubliere@hoist.tech",
        "email": "thomas.soubliere@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 218,
        "version": 1,
        "shortCode": "THARANGA.SAMARARATNA@HOIST.TECH",
        "name": "Tharanga Samararatna",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "tharanga.samararatna@hoist.tech",
        "email": "tharanga.samararatna@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 219,
        "version": 1,
        "shortCode": "TRACY.CORREIA@HOIST.TECH",
        "name": "Tracy Correia",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "tracy.correia@hoist.tech",
        "email": "tracy.correia@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 220,
        "version": 1,
        "shortCode": "UTHTHARA.KANAKARATNE@HOIST.TECH",
        "name": "Uththara Kanakaratne",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "uththara.kanakaratne@hoist.tech",
        "email": "uththara.kanakaratne@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 221,
        "version": 1,
        "shortCode": "VATHSALA.KALUARACHCHI@HOIST.TECH",
        "name": "Vathsala Kaluarachchi",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "vathsala.kaluarachchi@hoist.tech",
        "email": "vathsala.kaluarachchi@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 222,
        "version": 1,
        "shortCode": "VIRAJ.WICKRAMASINGHE@HOIST.TECH",
        "name": "Viraj Wickramasinghe",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "viraj.wickramasinghe@hoist.tech",
        "email": "viraj.wickramasinghe@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 224,
        "version": 1,
        "shortCode": "WARANGA.SAMARASINGHE@HOIST.TECH",
        "name": "Waranga Samarasinghe",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "waranga.samarasinghe@hoist.tech",
        "email": "waranga.samarasinghe@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    },
    {
        "id": 603,
        "version": 1,
        "shortCode": "JAGAN.AKULA@HOIST.TECH",
        "name": "Jagan Akula",
        "richRemarks": {},
        "csgId": 0,
        "emailAddress": "jagan.akula@hoist.tech",
        "email": "jagan.akula@hoist.tech",
        "systemRecord": false,
        "dtoName": "AssystUserDto",
        "anonymousRecord": false,
        "record": true
    }
]